version: "3"
services:
  gyant-challenge-app:
    build: .
    ports:
      - "3000:3000"
    networks:
      - gyant
    healthcheck:
          test: [ "CMD", "curl", "-f", "http://localhost:3000" ]
          interval: 30s
          timeout: 10s
          retries: 5
  gyant-challenge-tests:
    build: ./automation
    volumes:
      - ./automation:/app
    networks:
      - gyant
    depends_on:
      - gyant-challenge-app
networks:
  gyant:
    driver: "bridge"